### ISSUE TITLE
reproducible engine build

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/meta-flutter#271]
Requirement is to support a reproducible engine library.

This means the file can be compared to prior build, and there is not difference.

The solution revolves around removal of .git folders and any processes dependent on the .git folder.

## Round 1
```
gclient sync --revision ada363ee93b17cfe31587b5102679885cb40837e --no-history --shallow
find . -name .git -type d -print0|xargs -0 rm -r --
./flutter/tools/gn --unoptimized --no-goma
```
It fails with 
```
Generating GN files in: out/host_debug_unopt
ERROR at //flutter/shell/version/version.gni:17:7: Script returned non-zero exit code.
      exec_script("//flutter/build/git_revision.py",
      ^----------
Current dir: /mnt/raid10/flutter-engine/src/out/host_debug_unopt/
Command: vpython3 /mnt/raid10/flutter-engine/src/flutter/build/git_revision.py --repository /mnt/raid10/flutter-engine/src/flutter
Returned 1.
stderr:

fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/mnt/raid10/flutter-engine/src/flutter/build/git_revision.py", line 58, in <module>
    sys.exit(main())
  File "/mnt/raid10/flutter-engine/src/flutter/build/git_revision.py", line 51, in main
    version = get_repository_version(repository)
  File "/mnt/raid10/flutter-engine/src/flutter/build/git_revision.py", line 28, in get_repository_version
    version = subprocess.check_output([
  File "/home/joel/depot_tools/.cipd_bin/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/joel/depot_tools/.cipd_bin/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '-C', '/mnt/raid10/flutter-engine/src/flutter', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

See //flutter/tools/path_ops/BUILD.gn:5:1: whence it was imported.
import("//flutter/shell/version/version.gni")
^-------------------------------------------
See //flutter/BUILD.gn:93:9: which caused the file to be included.
        "//flutter/tools/path_ops",
        ^-------------------------
```

I update `flutter/build/git_revision.py` to return value of the engine I just pulled:

```
def get_repository_version(repository):
  return 'ada363ee93b17cfe31587b5102679885cb40837e'
```

`./flutter/tools/gn --unoptimized --no-goma` returns without error. 

Build attempt fails with:
```
 ./flutter/tools/gn --unoptimized --no-goma --no-prebuilt-dart-sdk
Generating GN files in: out/host_debug_unopt
Generating compile_commands took 25ms
Done. Made 1276 targets from 349 files in 946ms
[joel@air src]$ ninja -C out/host_debug_unopt
ninja: Entering directory `out/host_debug_unopt'
[0/1] Regenerating ninja files
...
[0/1] Regenerating ninja files
ninja: error: manifest 'build.ninja' still dirty after 100 tries

```

More later

**Comment by jwinarske** [comment]
Picking this back up. Two things have changed since the Round 1 notes above: the engine moved into the `flutter/flutter` monorepo (so the `gclient sync` / `src/flutter` paths here are stale), and the recipe now structures the checkout differently. Re-reading the notes against current master, the approach in Round 1 was working against itself.

## Round 1's premise caused both failures it recorded

The stated direction was "removal of `.git` folders and any processes dependent on the `.git` folder". Both recorded errors are downstream of that removal:

- `git_revision.py` failing with `fatal: not a git repository` is directly caused by deleting `.git`. The engine *wants* that metadata.
- Patching `get_repository_version()` to return a constant then papers over it, but `version.gni` calls it through `exec_script()`, so it is a gn input evaluated on every regen. The `manifest 'build.ninja' still dirty after 100 tries` loop that followed is consistent with having perturbed a gn input, though that one is worth re-testing rather than assuming.

The current recipe takes the opposite approach and is better for it: `EXTRA_GN_SYNC ?= "--shallow --no-history -R -D"` gives the shallow checkout without history, `.git` stays in place, and `SRCREV_flutter_sdk` is pinned via `get_flutter_hash()`. That makes `git_revision.py` deterministic by construction — it returns the pinned SHA every time. So the version-stamping half of this issue is effectively solved, and not in the way the notes above proposed.

## What actually stands between here and a byte-identical engine

1. **`zip -r engine_sdk.zip sdk`** (`flutter-engine_git.bb:530`). zip stores mtimes and writes entries in readdir order, and it has no `SOURCE_DATE_EPOCH` support. Two builds from identical inputs produce byte-different archives regardless of what the binaries inside do. Fixable by normalizing mtimes and feeding a sorted file list, but the better answer is to stop shipping a zip at all — see #288, where the same archive is what defeats uninative relocation.

2. **Build paths embedded in the binaries.** `GN_ARGS` passes `--target-sysroot ${STAGING_DIR_TARGET}`, which is a `TMPDIR`-rooted path, and `--no-stripped` is set with the unstripped copies retained in the install. The gn build does not consume OE's `DEBUG_PREFIX_MAP`, so those paths land in debug info and ship. Anyone comparing two builds from different `TMPDIR`s will see this before they see anything interesting.

3. **`SOURCE_DATE_EPOCH` is available but unplumbed.** `bitbake.conf` exports it into every task, so it is already in the engine build's environment; nothing in meta-flutter passes it through to the gn args or uses it for archive timestamps. It is there for the taking.

4. **Prebuilt Dart SDK.** With `PACKAGECONFIG[prebuilt-dart-sdk]` enabled the build pulls a pinned CIPD artifact. That is byte-stable, so it does not block reproducibility in the compare-two-builds sense, but it does mean the result is not reproducible *from source*. Worth deciding which of the two definitions this issue is chasing, because it changes whether `--no-prebuilt-dart-sdk` is a requirement or an option.

## Suggested way to work it

Rather than reasoning about it, build the engine twice into different `TMPDIR`s and run `diffoscope` over the outputs. oe-core already ships the harness for this in `meta/lib/oeqa/selftest/cases/reproducible.py`. That turns this issue into a concrete diff list and will almost certainly surface (1) and (2) immediately, which are the cheap wins.

Ordering suggestion: drop the zip first. It is the smallest change, it is a prerequisite for any meaningful byte comparison of the SDK payload, and it resolves the mechanism blocking #288 at the same time.

**Comment by jwinarske** [comment]
Ran the two-build comparison I suggested in the last comment.  It reproduces.

Setup: one build dir, shared SSTATE_DIR for the dependencies, no SSTATE_MIRRORS so nothing could restore a ready-made engine, `bitbake -c cleansstate flutter-engine` between the two runs, and different TMPDIRs (tmp-a, tmp-b).  qemux86-64, release mode, 3.47.5, PACKAGECONFIG without prebuilt-dart-sdk -- so this is reproducible *from source*, not just by comparison.

| | |
|---|---|
| packaged files, 35 of them | all byte-identical |
| deployed host tools, 7 binaries | all byte-identical |
| libflutter_engine.so build-id | 04c22850b3090eb27f1680a30ab8d1a2c70cd2ab, both |
| args.gn (deployed, not packaged) | differs -- records the TMPDIR-rooted sysroot |

That covers libflutter_engine.so, libimpeller.so, icudtl.dat, the .TOC files, gen_snapshot and the rest of the host tools.

## What fixed it, and what I had wrong

Neither was aimed at this issue -- both came out of #1009:

- the zip is gone.  That was blocker 1 in my last comment: zip stores mtimes and readdir order with no SOURCE_DATE_EPOCH support, so two identical builds produced different archives.
- args.gn is no longer packaged.  It was the only shipped file still carrying a TMPDIR path.

Blocker 2 in that comment was wrong.  I said the gn build does not consume DEBUG_PREFIX_MAP so build paths land in debug info and ship.  Measured while doing #961: gen_snapshot unstripped reports `DW_AT_comp_dir: out/linux_release_x64`, relative, and strings finds no TMPDIR in any packaged or deployed binary.  gn compiles from the out dir with relative source paths, so there was never a path to embed.  The recipe's own prefix map is belt and braces over that.

Blocker 3, SOURCE_DATE_EPOCH unplumbed, is moot now that the archive it mattered for is gone.

Blocker 4, prebuilt-dart-sdk, is answered by building without it, which is what the run above did.

## Keeping this open, narrowed

One target, one runtime mode, one machine, varying TMPDIR only.  Not varied: hostname, user, PATH, build date, or a second host.  So the claim is "reproducible across build directories", which is what Round 1 was chasing, not a full rebuild-elsewhere claim.

Left to check:
- the other runtime modes, debug and profile in particular, where the dart runtime mode differs
- a non-x86 target
- a second machine, or at least a varied hostname/user/date
