### ISSUE TITLE
flutter-auto long term stability

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/meta-flutter#320]
Just an update from our side:
We were able to revert back to Flutter version 3.3.7 and get flutter-auto working with our application. We have been testing the stability of running our application with `flutter-auto` over the last several weeks. Unfortunately we are seeing issues that the application sometimes stops updating the screen (animation on home screen stops, no screen updates on user input). The application is still running and still communicates with our back-end so it seems that only the screen updating is broken. There are no crash reports or debug messages printed when this happens so we are unsure if the issue is caused by `flutter-auto` or our application. Restarting the application resolves the issue for a while, but after a few days the same thing happens again (screen freezes/stops updating).
In parallel we have also some devices running our application with the `flutter-pi` embedder and on these devices we have never seen this problem. Some of these devices have ben running for > 2 weeks without problems.

Are there any known stability issues with flutter-auto that could explain this behavior? We typically only see this happening after the application has been running for a few days.

_Originally posted by @X-Terminator in https://github.com/meta-flutter/meta-flutter/issues/295#issuecomment-1697179264_

**Comment by jwinarske** [comment]
@X-Terminator  Thanks for the update.

For our cases we run x64 containers, x64 desktop (fedora/ubuntu), and aarch64 targets (yocto dunfell/kirkstone).  No sign of a problem similar to your report.

There are many variables in a problem like this.  In order to narrow this down, the expected order to deal with this is to come up with a minimum viable repro.  The smallest possible scenario that replicates the problem.

Note that I am prepping the OSS release for ivi-homescreen -> flutter-auto.  I should have it completed by end of day Wednesday (US).

So between the two the recommendation is update to latest release when it comes out, then attempt to repro your stability problem.

Also the upstream authority for ivi-homescreen/flutter-auto is https://github.com/toyota-connected/ivi-homescreen.  So if issue is related to flutter-auto only, then it's best to raise an issue there.

**Comment by jwinarske** [comment]
@X-Terminator Another data point.  flutter-auto is ivi-homescreen with some changes specific to AGL; which won't get picked up by Toyota.  Unless you need the AGL-Compositor you would just use ivi-homescreen recipe.

**Comment by jwinarske** [comment]
@X-Terminator
I have a repro on a TI SK-TDA4VM (j721e) (Arago tisdk-image-base, libweston-10_10.0.2, libgcc1_11.3.0).  What hardware/BSP and wayland compositor, weston+gcc versions hit the issue?

```
(gdb) info threads
  Id   Target Id                                          Frame 
* 1    Thread 0xffffb9a42020 (LWP 2413) "homescreen"      0x0000ffffb957c96c in ?? () from /lib/libc.so.6
  2    Thread 0xffffb92ff0a0 (LWP 2414) "homescreen"      0x0000ffffb957c96c in ?? () from /lib/libc.so.6
  3    Thread 0xffffb57580a0 (LWP 2415) "homescreen"      0x0000ffffb957c96c in ?? () from /lib/libc.so.6
  4    Thread 0xffffae9ee0a0 (LWP 2416) "io.flutter.ui"   0x0000ffffb95e7dc4 in epoll_pwait () from /lib/libc.so.6
  5    Thread 0xffffae1de0a0 (LWP 2417) "homescreen"      0x0000ffffb95de1a0 in poll () from /lib/libc.so.6
  6    Thread 0xffffad9ce0a0 (LWP 2418) "io.flutter.io"   0x0000ffffb95e7dc4 in epoll_pwait () from /lib/libc.so.6
  7    Thread 0xffff9ffff0a0 (LWP 2419) "io.worker.1"     0x0000ffffb957c96c in ?? () from /lib/libc.so.6
  8    Thread 0xffff9f7ef0a0 (LWP 2420) "io.worker.2"     0x0000ffffb957c96c in ?? () from /lib/libc.so.6
  9    Thread 0xffffad1be0a0 (LWP 2421) "dart:io EventHa" 0x0000ffffb95e7dc4 in epoll_pwait () from /lib/libc.so.6
(gdb) bt 10
#0  0x0000ffffb957c96c in ?? () from /lib/libc.so.6
#1  0x0000ffffb957f698 in pthread_cond_wait () from /lib/libc.so.6
#2  0x0000ffffb9986c84 in wl_display_read_events () from /usr/lib/libwayland-client.so.0
#3  0x0000aaaac8aefea8 in ?? ()
#4  0x0000ffffb952b230 in ?? () from /lib/libc.so.6
#5  0x0000ffffb952b30c in __libc_start_main () from /lib/libc.so.6
#6  0x0000aaaac8af3670 in ?? ()
```
@mv0 Does this ring a bell?

**Comment by jwinarske** [comment]
I raised TI issue here:
https://e2e.ti.com/support/processors-group/processors/f/processors-forum/1280666/sk-tda4vm-rogue-powervr-display-driver-stability

**Comment by jwinarske** [comment]
Gone stale
