### ISSUE TITLE
Add flutter_news_example

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/meta-flutter#443]
https://github.com/flutter/news_toolkit
https://github.com/googleads/googleads-mobile-flutter

The Android plugin uses Variant type 129, which is not supported in C++ at this time.  Custom code required on embedder side to support this.

**Comment by jwinarske** [comment]
Firebase needs updating in example.  I get:
```
[09:17:05.634281] [D] Channel: "dev.flutter.pigeon.FirebaseCoreHostApi.initializeCore"

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized.

Usually this means you've attempted to use a Firebase service before calling `Firebase.initializeApp`.

View the documentation for more information: https://firebase.flutter.dev/docs/overview#initialization
    
#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:120:9)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#2      bootstrap (package:flutter_news_example/main/bootstrap/bootstrap.dart:26:3)
<asynchronous suspension>
```

**Comment by jwinarske** [comment]
won't fix
