### ISSUE TITLE
[pdfium] x64 compilation failing

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/meta-flutter#601]
nasm issue

```
| FAILED: obj/third_party/libjpeg_turbo/simd_asm/jccolor-avx2.o
| python3 ../build/gn_run_binary.py nasm -DPIC -felf64 -I../third_party/libjpeg_turbo/simd/nasm// -I../third_party/libjpeg_turbo/simd/x86_64// -I./ -I../ -Igen/ -D__x86_64__ -DPIC -DELF -MD obj/third_party/libjpeg_turbo/simd_asm/jccolor-avx2.o.d -o obj/third_party/libjpeg_turbo/simd_asm/jccolor-avx2.o ../third_party/libjpeg_turbo/simd/x86_64/jccolor-avx2.asm
| Traceback (most recent call last):
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/pdfium/out/../build/gn_run_binary.py", line 26, in <module>
|     ret = subprocess.call(args)
|           ^^^^^^^^^^^^^^^^^^^^^
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 389, in call
|     with Popen(*popenargs, **kwargs) as p:
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 1955, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: './nasm'
| [1145/1188] ACTION //third_party/libjpeg_turbo:simd_asm_action(//build/toolchain/linux:x64)
| FAILED: obj/third_party/libjpeg_turbo/simd_asm/jcgray-avx2.o
| python3 ../build/gn_run_binary.py nasm -DPIC -felf64 -I../third_party/libjpeg_turbo/simd/nasm// -I../third_party/libjpeg_turbo/simd/x86_64// -I./ -I../ -Igen/ -D__x86_64__ -DPIC -DELF -MD obj/third_party/libjpeg_turbo/simd_asm/jcgray-avx2.o.d -o obj/third_party/libjpeg_turbo/simd_asm/jcgray-avx2.o ../third_party/libjpeg_turbo/simd/x86_64/jcgray-avx2.asm
| Traceback (most recent call last):
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/pdfium/out/../build/gn_run_binary.py", line 26, in <module>
|     ret = subprocess.call(args)
|           ^^^^^^^^^^^^^^^^^^^^^
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 389, in call
|     with Popen(*popenargs, **kwargs) as p:
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 1955, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: './nasm'
| [1146/1188] ACTION //third_party/libjpeg_turbo:simd_asm_action(//build/toolchain/linux:x64)
| FAILED: obj/third_party/libjpeg_turbo/simd_asm/jcgray-sse2.o
| python3 ../build/gn_run_binary.py nasm -DPIC -felf64 -I../third_party/libjpeg_turbo/simd/nasm// -I../third_party/libjpeg_turbo/simd/x86_64// -I./ -I../ -Igen/ -D__x86_64__ -DPIC -DELF -MD obj/third_party/libjpeg_turbo/simd_asm/jcgray-sse2.o.d -o obj/third_party/libjpeg_turbo/simd_asm/jcgray-sse2.o ../third_party/libjpeg_turbo/simd/x86_64/jcgray-sse2.asm
| Traceback (most recent call last):
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/pdfium/out/../build/gn_run_binary.py", line 26, in <module>
|     ret = subprocess.call(args)
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 1955, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: './nasm'
| [1170/1188] ACTION //third_party/libjpeg_turbo:simd_asm_action(//build/toolchain/linux:x64)
| FAILED: obj/third_party/libjpeg_turbo/simd_asm/jquanti-avx2.o
| python3 ../build/gn_run_binary.py nasm -DPIC -felf64 -I../third_party/libjpeg_turbo/simd/nasm// -I../third_party/libjpeg_turbo/simd/x86_64// -I./ -I../ -Igen/ -D__x86_64__ -DPIC -DELF -MD obj/third_party/libjpeg_turbo/simd_asm/jquanti-avx2.o.d -o obj/third_party/libjpeg_turbo/simd_asm/jquanti-avx2.o ../third_party/libjpeg_turbo/simd/x86_64/jquanti-avx2.asm
| Traceback (most recent call last):
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/pdfium/out/../build/gn_run_binary.py", line 26, in <module>
|     ret = subprocess.call(args)
|           ^^^^^^^^^^^^^^^^^^^^^
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 389, in call
|     with Popen(*popenargs, **kwargs) as p:
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/__w/meta-flutter/scarthgap-linux-dummy/build/tmp/work/core2-64-poky-linux/pdfium/130.0.6721.0/recipe-sysroot-native/usr/share/depot_tools/.cipd_bin/3.11/lib/python3.11/subprocess.py", line 1955, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: './nasm'
```

**Comment by WAKazuyoshiAkiyama** [comment]
I got the same error on `kirkstone`.

**Comment by jwinarske** [comment]
Resolved with https://github.com/meta-flutter/meta-flutter/pull/628
